#!/bin/bash

if [ $1 == "configure" ]; then

    if ! grep -qw SWAPNOUSE /etc/default/zram-swap; then
        echo "
# don't use these swappartitions
SWAPNOUSE='/dev/sda21,/dev/mmcblk0p99'
" >> /etc/default/zram-swap 
    fi

#    dpkg-trigger --no-await trigger-xbian-package-zram-swap

    echo "xbian-package-zram-swap" >>  /run/reboot-required

elif [ $1 = triggered ]; then

    :
#    stop -q zram-swap 2>/dev/null|| :
#    start -q zram-swap DPKG=yes 2>/dev/null|| :

fi

exit 0
